### ISSUE TITLE
BAG plugin

### ISSUE THREAD

**Issue by giumas** [HDFGroup/hdf-compass#80]
On my [fork](https://github.com/giumas/hdf-compass/tree/bag_ahead), I am working on a plugin for BAG data files.

For people that has never heard about it, the BAG  is a non-proprietary file format for storing and exchanging bathymetric data developed by the [Open Navigation Surface Working Group](http://www.opennavsurf.org/) that is widely used in hydrography and ocean mapping.

Some informative links on the format:

* https://marinemetadata.org/references/bag
* https://www.ngdc.noaa.gov/mgg/bathymetry/hydro.html
* http://www.gdal.org/frmt_bag.html

The plugin uses `hydroffice.bag`, a pure-Python BSD-like library that has been developing in parallel with the plugin. The library is available from this repository: https://bitbucket.org/ccomjhc/hyo_bag/overview

**Comment by jreadey** [comment]
@giumas - thanks for the info.  Hopefully it will bring in some others interested in BAG.

I assume you'll be merging in changes from the develop branch as we go along?

**Comment by giumas** [comment]
@jreadey : I have a very first draft implementation of the BAG plugin with the extended model for XML/Text nodes (https://github.com/HDFGroup/hdf-compass/issues/69). It would be great if you could give a look on how it looks like to you: https://bitbucket.org/ccomjhc/hyo_bag/downloads

**Comment by giumas** [comment]
@jreadey Under a menu there is a "Open samples..." item that open the file dialog with 2 tiny BAG example files

**Comment by giumas** [comment]
> I assume you'll be merging in changes from the develop branch as we go along?

As soon as you give me a feedback on the [Xml](https://github.com/giumas/hdf-compass/blob/bag_ahead/hdf_compass/compass_model/model.py#L430-L449) node amd XmlFrame(https://github.com/giumas/hdf-compass/blob/bag_ahead/hdf_compass/compass_viewer/text/frame.py#L108-L379) I can start to push PRs.

**Comment by jreadey** [comment]
@giumas - looks good! 
The font size in the XML display seem to vary strangely.  Is this something you can adjust?

**Comment by giumas** [comment]
@jreadey : I can surely control the font size, but I am not sure that I understand 
> The font size in the XML display seem to vary strangely

Could you drop here a screenshot of what you mean?

**Comment by jreadey** [comment]
Sure.  Here it is:
<img width="571" alt="bagexplore_xml" src="https://cloud.githubusercontent.com/assets/7785492/10403540/40f64da4-6e81-11e5-8808-ddd5993a9fbe.png">

**Comment by giumas** [comment]
@jreadey It is fun.. since I actually struggled to create that "strange" output. My intent was to highlight the text in place of the xml tags.. I will work on a better way to make it.

**Comment by giumas** [comment]
The BAG plugin requires the `hydroffice.bag` package that can be installed by `pip install hydroffice.bag` (it has as dependencies `h5py` and `lxml`).

**Comment by jreadey** [comment]
@giumas - I wasn't able to do a pip install of the bag package:
```
$ pip install hdroffice.bag
Collecting hdroffice.bag
  Could not find a version that satisfies the requirement hdroffice.bag (from versions: )
No matching distribution found for hdroffice.bag
```
Installing bag from a clean Python environment failed as well. But this time the error was:
```
ImportError: No module named Cython.Build

  ----------------------------------------
  Failed building wheel for h5py
```

**Comment by giumas** [comment]
@jreadey Did you mispelled it? Did you type 'pip install hydroffice.bag'?

The second fail is expected for the platforms where h5py is not on pypi.. but if you install h5py by other sources, the 'python setup.py install' should work and install hydroffice.bag.

**Comment by jreadey** [comment]
@giumas I created a new environment in Anaconda, did a "conda install h5py" (which brings in the hdf5 libraries, and the did pip install hydroffice.bag.  This is the complete output:
```
(bag)Cardinal:~ jreadey$ pip install hydroffice.bag
Collecting hydroffice.bag
  Using cached hydroffice.bag-0.2.2-py2.py3-none-any.whl
Collecting lxml (from hydroffice.bag)
  Using cached lxml-3.4.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): h5py in ./anaconda/envs/bag/lib/python2.7/site-packages (from hydroffice.bag)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.1 in ./anaconda/envs/bag/lib/python2.7/site-packages (from h5py->hydroffice.bag)
Requirement already satisfied (use --upgrade to upgrade): six in ./anaconda/envs/bag/lib/python2.7/site-packages (from h5py->hydroffice.bag)
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml
  Complete output from command /Users/jreadey/anaconda/envs/bag/bin/python -c "import setuptools;__file__='/private/var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-build-m7bE2F/lxml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/tmpoQjKWrpip-wheel-:
  /Users/jreadey/anaconda/envs/bag/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  Building lxml version 3.4.4.
  Building without Cython.
  Using build configuration of libxslt 1.1.28
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.5-x86_64-2.7
  creating build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/builder.py -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/sax.py -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.macosx-10.5-x86_64-2.7/lxml
  creating build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  creating build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/html
  creating build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.5-x86_64-2.7/lxml
  copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
  creating build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources
  creating build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/rng
  creating build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.5-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.macosx-10.5-x86_64-2.7
  creating build/temp.macosx-10.5-x86_64-2.7/src
  creating build/temp.macosx-10.5-x86_64-2.7/src/lxml
  gcc -fno-strict-aliasing -I/Users/jreadey/anaconda/envs/bag/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/libxml2 -I/private/var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-build-m7bE2F/lxml/src/lxml/includes -I/Users/jreadey/anaconda/envs/bag/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.5-x86_64-2.7/src/lxml/lxml.etree.o -w -flat_namespace
  In file included from src/lxml/lxml.etree.c:239:
  /private/var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-build-m7bE2F/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
  #include "libxml/xmlversion.h"
           ^
  1 error generated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for lxml
Failed to build lxml
Installing collected packages: lxml, hydroffice.bag
  Running setup.py install for lxml
    Complete output from command /Users/jreadey/anaconda/envs/bag/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-build-m7bE2F/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-je3kvq-record/install-record.txt --single-version-externally-managed --compile:
    /Users/jreadey/anaconda/envs/bag/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.4.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    running install
    running build
    running build_py
    copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.5-x86_64-2.7/lxml/includes
    running build_ext
    building 'lxml.etree' extension
    gcc -fno-strict-aliasing -I/Users/jreadey/anaconda/envs/bag/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/libxml2 -I/private/var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-build-m7bE2F/lxml/src/lxml/includes -I/Users/jreadey/anaconda/envs/bag/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.5-x86_64-2.7/src/lxml/lxml.etree.o -w -flat_namespace
    In file included from src/lxml/lxml.etree.c:239:
    /private/var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-build-m7bE2F/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
    #include "libxml/xmlversion.h"
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/Users/jreadey/anaconda/envs/bag/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-build-m7bE2F/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-je3kvq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/dl/1f9z17n13mn4gxvy7cbdb_200000gn/T/pip-build-m7bE2F/lxml
```

**Comment by giumas** [comment]
The issue is clearly that lxml fails to build, not related to hydroffice.bag. Try 'conda install lxml' that is actually  the way that I tested on Mac..

**Comment by jreadey** [comment]
Yes, if I install lxlm then the hydroffice.bat install works.  Shouldn't the hyrdrooffice.bat package list lxml as a dependency so that the pip install will automatically pull in lxml?

**Comment by giumas** [comment]
Actually, lxml is listed (line 108):

https://bitbucket.org/ccomjhc/hyo_bag/src/d0ba26f29d1b88b2317149d6f8a6eabd1afbe746/setup.py?at=0.2.2&fileviewer=file-view-default

The issue on Mac for lxml could be related to your environment:

http://stackoverflow.com/questions/19548011/cannot-install-lxml-on-mac-os-x-10-9

However, I don't believe that these 2 dependencies are really an issue:

- h5py is also required for the HDF5 model
- lxml is a so popular library that is quite easy yo find online help to install it

**Comment by jreadey** [comment]
@giumas - I'm running into a problem creating the install image on Mac OS  X 10.8.

I can run Compass from the source tree & the BAG plugin loads correctly.

I built using the 1folder.spec file:
```
$ pyinstaller HDFCompass.1folder.spec
```
PyInstaller succeeded in creating the executable.  However running the app fails on startup:
```
$dist/HDFCompass.app/Contents/MacOS/HDFCompass 
Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "/Users/jreadey/hdf-compass/hdf_compass/compass_viewer/__init__.py", line 221, in run
    load_plugins()
  File "/Users/jreadey/hdf-compass/hdf_compass/compass_viewer/__init__.py", line 197, in load_plugins
    from hdf_compass import bag_model
  File "/private/var/folders/fb/nggl4g7x1hn1m4pb991qn1sw0000gn/T/pip-build-Lxhfr2/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/Users/jreadey/hdf-compass/hdf_compass/bag_model/__init__.py", line 16, in <module>
    from .model import BAGStore, BAGDataset, BAGGroup, BAGImage, BAGKV
  File "/private/var/folders/fb/nggl4g7x1hn1m4pb991qn1sw0000gn/T/pip-build-Lxhfr2/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/Users/jreadey/hdf-compass/hdf_compass/bag_model/model.py", line 23, in <module>
    from hydroffice.bag import is_bag
  File "/private/var/folders/fb/nggl4g7x1hn1m4pb991qn1sw0000gn/T/pip-build-Lxhfr2/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/usr/local/lib/python2.7/site-packages/hydroffice/bag/__init__.py", line 13, in <module>
    from .bag import BAGFile
  File "/private/var/folders/fb/nggl4g7x1hn1m4pb991qn1sw0000gn/T/pip-build-Lxhfr2/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/usr/local/lib/python2.7/site-packages/hydroffice/bag/bag.py", line 9, in <module>
    from lxml import isoschematron
  File "/private/var/folders/fb/nggl4g7x1hn1m4pb991qn1sw0000gn/T/pip-build-Lxhfr2/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/usr/local/lib/python2.7/site-packages/lxml/isoschematron/__init__.py", line 51, in <module>
    os.path.join(_resources_dir, 'xsl', 'XSD2Schtrn.xsl')))
  File "lxml.etree.pyx", line 3310, in lxml.etree.parse (src/lxml/lxml.etree.c:72517)
  File "parser.pxi", line 1791, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:105979)
  File "parser.pxi", line 1817, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:106278)
  File "parser.pxi", line 1721, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:105277)
  File "parser.pxi", line 1122, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:100227)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 618, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94818)
IOError: Error reading file '/Users/jreadey/hdf-compass/dist/HDFCompass.app/Contents/MacOS/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl': failed to load external entity "/Users/jreadey/hdf-compass/dist/HDFCompass.app/Contents/MacOS/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl"
HDFCompass returned -1
```

Any ideas on what is going wrong?

**Comment by giumas** [comment]
@jreadey : the issue is with the pyinstaller hook for lxml (it does not collect the Schematron files, they are not so commonly used). I will push a PR to pyinstaller soon.. In the mean time I will provide a patch to the HDF Compass spec (once that I will get a more stable internet connection).

**Comment by giumas** [comment]
This PR should solve the problem without the need to manually modifying the .spec files: https://github.com/pyinstaller/pyinstaller/issues/1613

**Comment by giumas** [comment]
@jreadey : this is a temporary patch: https://github.com/HDFGroup/hdf-compass/pull/105

I would propose to close this enhancement ticket once that @jreadey get a frozen application.

**Comment by jreadey** [comment]
@giumas - succes creating frozen app for Mac and Windows!
On Linux I did a pip install lxml and got the following error:

```
src/lxml/lxml.etree.c:200893: error: ‘XML_XPATH_INVALID_CTXT_POSITION’ undeclared (first use in this function)
    src/lxml/lxml.etree.c:201123: error: ‘LIBXSLT_VERSION’ undeclared (first use in this function)
    src/lxml/lxml.etree.c:201135: error: ‘xsltLibxsltVersion’ undeclared (first use in this function)
    src/lxml/lxml.etree.c:201147: error: ‘__pyx_v_4lxml_5etree_XSLT_DOC_DEFAULT_LOADER’ undeclared (first use in this function)
    src/lxml/lxml.etree.c:201147: error: ‘xsltDocDefaultLoader’ undeclared (first use in this function)
    src/lxml/lxml.etree.c:201156: error: ‘xsltDocLoaderFunc’ undeclared (first use in this function)
    src/lxml/lxml.etree.c:201156: error: expected ‘)’ before ‘__pyx_f_4lxml_5etree__xslt_doc_loader’
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-k5XFuC/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-qaiVia-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-k5XFuC/lxml
```

Do you think this is this an issue with lxml or is it related to my build environment somehow?

**Comment by ajelenak-thg** [comment]
Do you have libxml and libxslt header files? Those are typically available in the development packages?

**Comment by giumas** [comment]
I have found these SO questions that seem to suggest a solution that looks like `sudo yum install -y gcc ruby-devel libxml2 libxml2-devel libxslt libxslt-devel`:

* http://stackoverflow.com/questions/4642942/setup-py-install-lxml-with-python2-6-on-centos
* http://stackoverflow.com/questions/20886069/cant-install-lxml-on-centos

**Comment by giumas** [comment]
Running the command suggested here: http://stackoverflow.com/a/14744356/2741329 I was able to build ``lxml`` on Centos. So I close this ticket that was about a first implementation of the plugin. One of the future improvement is described here: https://github.com/HDFGroup/hdf-compass/issues/80

**Comment by jreadey** [comment]
I'm able to run the BAG plugin on Linux using the yum install packages @giumas noted above.
